### ISSUE TITLE
can't load `libfontconfig` on OS X 10.12

### ISSUE THREAD

**Issue by mbutterick** [takikawa/racket-fontconfig#1]
The repo in its current state will work on OS X 10.14 (Mojave), but on 10.12 (Sierra) I get this error:

```
ffi-lib: couldn't open "libfontconfig.dylib" 
(dlopen(libfontconfig.dylib, 6): image not found)
```

**Comment by mbutterick** [comment]
The `fc-lib` load line is this:

```
(define fc-lib (ffi-lib "libfontconfig"))
```

But on Sierra needs to be:

```
(define fc-lib (ffi-lib "libfontconfig" '("1")))
```

**Comment by takikawa** [comment]
I don't have a good way to test this myself, but I can change the definition to
```
(define fc-lib (ffi-lib "libfontconfig" '("1" #f)))
```
 which I suspect would work on both.

**Comment by mbutterick** [comment]
I’m really dumb with FFI things, so take this FWIW: On further testing, it seems to be related not to Mojave vs. Sierra, but that I have some other `libfontconfig` lurking on the Mojave machine which is being picked up by `(ffi-lib "libfontconfig")` (because it searches into the system dylibs) but not by `(ffi-lib "libfontconfig" '("1"))` (because that’s the one that ships with Racket). So I’d suppose that if code that relies on `racket-fontconfig` is intended to be portable between Rackets, it should be qualified in a way that forces it to choose the Racket-supplied `fontconfig`.

**Comment by takikawa** [comment]
I think having the `#f` fallback should make this work how you'd like, in that it will prioritize the `"1"` case first and should pick up what Racket has. It'll only use the fallback if that can't be found for some reason (future proofing it in case Racket's native libs change or something).

I just pushed a commit for this, can adjust it if it doesn't work right after all.
